name: notes
description: A notes built with flutter

version: 0.0.7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: 1.1.2
  cupertino_icons: ^0.1.3
  flutter_staggered_grid_view: ^0.3.2
  auto_size_text: ^2.1.0
  sqflite:
  path:
  intl: ^0.16.1
  share: ^0.6.4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
